//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogExtensions.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index_Admin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_Admin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlogExtensions.Localization.Index.Admin", typeof(Index_Admin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already in use.
        /// </summary>
        public static string AlreadyInUse {
            get {
                return ResourceManager.GetString("AlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already signed in.
        /// </summary>
        public static string AlreadySignedIn {
            get {
                return ResourceManager.GetString("AlreadySignedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content can not be empty.
        /// </summary>
        public static string ContentNotEmpty {
            get {
                return ResourceManager.GetString("ContentNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drafts.
        /// </summary>
        public static string Drafts {
            get {
                return ResourceManager.GetString("Drafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown.
        /// </summary>
        public static string Markdown {
            get {
                return ResourceManager.GetString("Markdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Documentation.
        /// </summary>
        public static string MarkdownDocumentation {
            get {
                return ResourceManager.GetString("MarkdownDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Help.
        /// </summary>
        public static string MarkdownHelp {
            get {
                return ResourceManager.GetString("MarkdownHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For further Markdown syntax reference: .
        /// </summary>
        public static string MarkdownReference {
            get {
                return ResourceManager.GetString("MarkdownReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New post.
        /// </summary>
        public static string NewPost {
            get {
                return ResourceManager.GetString("NewPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New post .
        /// </summary>
        public static string NewPostTitle {
            get {
                return ResourceManager.GetString("NewPostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted in.
        /// </summary>
        public static string PostedIn {
            get {
                return ResourceManager.GetString("PostedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The post was saved successfully.
        /// </summary>
        public static string PostSaved {
            get {
                return ResourceManager.GetString("PostSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut.
        /// </summary>
        public static string Shortcut {
            get {
                return ResourceManager.GetString("Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slug.
        /// </summary>
        public static string Slug {
            get {
                return ResourceManager.GetString("Slug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slug can not be empty.
        /// </summary>
        public static string SlugNotEmpty {
            get {
                return ResourceManager.GetString("SlugNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something bad happened. Server reported .
        /// </summary>
        public static string SomethingBadHappened {
            get {
                return ResourceManager.GetString("SomethingBadHappened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please try again.
        /// </summary>
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this post?.
        /// </summary>
        public static string SureDeletePost {
            get {
                return ResourceManager.GetString("SureDeletePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to leave this page?.
        /// </summary>
        public static string SureLeave {
            get {
                return ResourceManager.GetString("SureLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title is already in use.
        /// </summary>
        public static string TitleInUse {
            get {
                return ResourceManager.GetString("TitleInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title can not be empty.
        /// </summary>
        public static string TitleNotEmpty {
            get {
                return ResourceManager.GetString("TitleNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Count.
        /// </summary>
        public static string WordCount {
            get {
                return ResourceManager.GetString("WordCount", resourceCulture);
            }
        }
    }
}
